// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYfh-f1k-7AQtccfeSPTvYmL18r3PuSpU',
    appId: '1:587441939174:web:9b45f63e7b011db7cc9127',
    messagingSenderId: '587441939174',
    projectId: 'course-app-a19ea',
    authDomain: 'course-app-a19ea.firebaseapp.com',
    storageBucket: 'course-app-a19ea.firebasestorage.app',
    measurementId: 'G-08J2Q2NWX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7qChf4fOcjzzcvliGk97kC--OZ08Vo44',
    appId: '1:587441939174:android:47df1ee61a9cd6f2cc9127',
    messagingSenderId: '587441939174',
    projectId: 'course-app-a19ea',
    storageBucket: 'course-app-a19ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkEjokid7seADIeSLKp9-_JXGTcgGuMaM',
    appId: '1:587441939174:ios:02590fe751c9a12dcc9127',
    messagingSenderId: '587441939174',
    projectId: 'course-app-a19ea',
    storageBucket: 'course-app-a19ea.firebasestorage.app',
    iosBundleId: 'com.example.courseManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkEjokid7seADIeSLKp9-_JXGTcgGuMaM',
    appId: '1:587441939174:ios:02590fe751c9a12dcc9127',
    messagingSenderId: '587441939174',
    projectId: 'course-app-a19ea',
    storageBucket: 'course-app-a19ea.firebasestorage.app',
    iosBundleId: 'com.example.courseManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYfh-f1k-7AQtccfeSPTvYmL18r3PuSpU',
    appId: '1:587441939174:web:57a220f568017e97cc9127',
    messagingSenderId: '587441939174',
    projectId: 'course-app-a19ea',
    authDomain: 'course-app-a19ea.firebaseapp.com',
    storageBucket: 'course-app-a19ea.firebasestorage.app',
    measurementId: 'G-16XKLP55R7',
  );
}
